export const LOAD_STORE_LIST = 'LOAD_STORE_LIST'

export const LOAD_AREA_LIST = 'LOAD_AREA_LIST'

export const LOAD_AREA_OPTIONS = 'LOAD_AREA_OPTIONS'
export const LOAD_REGIONS = 'LOAD_REGIONS'

export const LOAD_PROVINCE = 'LOAD_PROVINCE'

export const LOAD_MSG_LIST = 'LOAD_MSG_LIST'
export const LOAD_RECEIPT_LIST = 'LOAD_RECEIPT_LIST'

export const LOAD_COMMERCIAL_LIST = 'LOAD_COMMERCIAL_LIST'

export const SYNC_UPDATE_APPLET_BANNER = 'SYNC_UPDATE_APPLET_BANNER'
